admin_home:
    path:  /
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

admin_site_configurations:
    path:  /site/configurations
    defaults: { _controller: ObjectsAdminBundle:Admin:siteConfigurations }

admin_site_emails:
    path:  /site/emails
    defaults: { _controller: ObjectsAdminBundle:Admin:siteEmails }

# Sonata Admin Routes
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /
