<?php

namespace Objects\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends EntityRepository {

    /**
     * @author Mahmoud
     * @param array $bannersIds
     */
    public function increaseNumberOfViews(array $bannersIds) {
        if (count($bannersIds) > 0) {
            $this->getEntityManager()->createQuery('
                UPDATE ObjectsAdminBundle:Banner b
                set b.numberOfViews = b.numberOfViews + 1
                WHERE b.id IN(:bannersIds)
            ')->setParameter('bannersIds', $bannersIds)->execute();
        }
    }

    /**
     * @author Mahmoud
     * @param integer $id
     */
    public function incrementBannerNoOfClicksAction($id) {
        $this->getEntityManager()->createQuery('
            UPDATE ObjectsAdminBundle:Banner b
            set b.numberOfClicks = b.numberOfClicks + 1
            WHERE b.id = :id
            ')->setParameter('id', $id)->execute();
    }

}
